<?php
include "../../config/database.php";

$patients = mysqli_fetch_assoc(mysqli_query($conn,"SELECT COUNT(*) total FROM patients"))['total'];
$doctors = mysqli_fetch_assoc(mysqli_query($conn,"SELECT COUNT(*) total FROM doctors"))['total'];
$appointments = mysqli_fetch_assoc(mysqli_query($conn,"SELECT COUNT(*) total FROM appointments"))['total'];
$revenue = mysqli_fetch_assoc(mysqli_query($conn,"SELECT SUM(amount) total FROM billing"))['total'];

if(!$revenue) $revenue = 0;

$bills = mysqli_query($conn,"
SELECT
bill_id,
patient_name,
doctor_name,
amount,
bill_date,
status
FROM billing
ORDER BY bill_date DESC
LIMIT 10
");
?>

<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Hospital Report</title>

<style>

body{
font-family:Arial,sans-serif;
margin:30px;
color:#222;
}

h1{
text-align:center;
margin-bottom:5px;
}

h3{
text-align:center;
margin-top:0;
color:#666;
}

table{
width:100%;
border-collapse:collapse;
margin-top:20px;
}

table th,
table td{
border:1px solid #000;
padding:8px;
text-align:center;
}

th{
background:#0d6efd;
color:#fff;
}

.summary{
display:flex;
justify-content:space-between;
margin-top:20px;
}

.card{
width:23%;
border:1px solid #000;
padding:15px;
text-align:center;
font-weight:bold;
}

.footer{
margin-top:35px;
text-align:center;
font-size:13px;
color:#555;
}

@media print{

button{
display:none;
}

}

</style>

</head>

<body>

<button onclick="window.print()">Print Report</button>

<h1>MediCore Hospital Management System</h1>

<h3>Generated : <?php echo date("d-m-Y h:i A"); ?></h3>

<div class="summary">

<div class="card">
Patients<br><br>
<?php echo $patients; ?>
</div>

<div class="card">
Doctors<br><br>
<?php echo $doctors; ?>
</div>

<div class="card">
Appointments<br><br>
<?php echo $appointments; ?>
</div>

<div class="card">
Revenue<br><br>
₹ <?php echo number_format($revenue,2); ?>
</div>

</div>

<h2>Recent Bills</h2>

<table>
<tr>
<th>Bill ID</th>
<th>Patient</th>
<th>Doctor</th>
<th>Amount</th>
<th>Date</th>
<th>Status</th>
</tr>

<?php while($row=mysqli_fetch_assoc($bills)){ ?>

<tr>

<td><?php echo $row['bill_id']; ?></td>

<td><?php echo $row['patient_name']; ?></td>

<td><?php echo $row['doctor_name']; ?></td>

<td>₹ <?php echo number_format($row['amount'],2); ?></td>

<td><?php echo $row['bill_date']; ?></td>

<td><?php echo $row['status']; ?></td>

</tr>

<?php } ?>

</table>

<div class="footer">

Generated By : Admin<br>
MediCore Hospital Management System

</div>

<script>
window.onload=function(){
window.print();
}
</script>

</body>
</html>